services:
  - type: web
    name: convergent-tech-questionnaire
    runtime: node
    plan: free
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_VERSION
        value: 22.13.0
      - key: PNPM_VERSION
        value: 9.0.0
      - key: DATABASE_URL
        fromDatabase:
          name: convergent_db
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: OAUTH_SERVER_URL
        sync: false
      - key: BUILT_IN_FORGE_API_KEY
        sync: false
      - key: BUILT_IN_FORGE_API_URL
        sync: false
      - key: VITE_APP_TITLE
        value: "Convergent Technology"
      - key: VITE_APP_LOGO
        sync: false
      - key: VITE_ANALYTICS_ENDPOINT
        sync: false
      - key: VITE_ANALYTICS_WEBSITE_ID
        sync: false
      - key: VITE_APP_ID
        sync: false
      - key: VITE_OAUTH_PORTAL_URL
        sync: false
      - key: OWNER_NAME
        sync: false
      - key: OWNER_OPEN_ID
        sync: false

databases:
  - name: convergent_db
    databaseName: convergent_tech_db
    user: convergent_user
    plan: free

